/**
 * Emits `src/auth-schema.ts` (drizzle sqlite tables for Better Auth) from the
 * *installed* better-auth's own table definitions.
 *
 * We generate rather than use `@better-auth/cli`: the published CLI (1.4.x)
 * lags the runtime (1.7.x), so its output silently omits newer columns — e.g.
 * 1.7's `account.issuer` — and the adapter then fails at runtime with
 * `The field "issuer" does not exist in the schema for the model "account"`.
 * Reading `getSchema()` out of node_modules keeps the two in lockstep by
 * construction.
 *
 * Run: bun run auth:generate
 */
import { getSchema } from "better-auth/db";
import type { DBFieldAttribute } from "@better-auth/core/db";
import { authOptions } from "../src/auth-options";

const OUT = new URL("../src/auth-schema.ts", import.meta.url);

/** better-auth addresses columns by their logical (camelCase) field name, so
 *  that is the drizzle property name; the physical column is snake_case, which
 *  is what the drizzle adapter assumes by default (`camelCase: false`). */
const camel = (name: string) =>
  name.replace(/[_-](\w)/g, (_, c: string) => c.toUpperCase());

const snake = (name: string) =>
  name.replace(/([a-z0-9])([A-Z])/g, "$1_$2").toLowerCase();

const quote = (value: unknown) =>
  typeof value === "string" ? JSON.stringify(value) : String(value);

function column(field_: string, field: DBFieldAttribute): string {
  const name = snake(field_);
  const parts: string[] = [];

  switch (field.type) {
    case "boolean":
      parts.push(`integer(${quote(name)}, { mode: "boolean" })`);
      break;
    case "date":
      parts.push(`integer(${quote(name)}, { mode: "timestamp_ms" })`);
      break;
    case "number":
      parts.push(`integer(${quote(name)})`);
      break;
    default:
      // string, json, and array types all serialize to TEXT on sqlite.
      parts.push(`text(${quote(name)})`);
  }

  if (field.references) {
    const { model, field: target, onDelete = "cascade" } = field.references;
    parts.push(
      `.references(() => ${camel(model)}.${camel(target)}, { onDelete: ${quote(onDelete)} })`,
    );
  }

  const def = field.defaultValue;
  if (def !== undefined && typeof def !== "function") {
    parts.push(
      field.type === "boolean"
        ? `.default(${def ? "true" : "false"})`
        : `.default(${quote(def)})`,
    );
  }

  if (field.required !== false) parts.push(".notNull()");
  if (field.unique) parts.push(".unique()");

  return `  ${camel(field_)}: ${parts.join("")},`;
}

const schema = getSchema(authOptions({
  baseURL: "http://localhost",
  github: { clientId: "generate", clientSecret: "generate" },
}) as Parameters<typeof getSchema>[0]);

const tables = Object.entries(schema)
  .filter(([, table]) => !table.disableMigrations)
  .sort(([, a], [, b]) => a.order - b.order);

const body = tables.map(([tableName, table]) => {
  // `id` is implicit in better-auth's model definitions.
  const columns = ['  id: text("id").primaryKey(),']
    .concat(
      Object.entries(table.fields).map(([name, field]) =>
        column(name, field as DBFieldAttribute),
      ),
    )
    .join("\n");

  // Table-level indexes, plus the per-field `index: true` markers (which
  // better-auth keeps outside `table.indexes`).
  const indexes = (table.indexes ?? []).map((index) => {
    const cols = index.columns.map((c) => `t.${camel(c)}`).join(", ");
    const kind = index.unique ? "uniqueIndex" : "index";
    return `    ${kind}(${quote(index.name)}).on(${cols}),`;
  });

  for (const [name, field] of Object.entries(table.fields)) {
    const attr = field as DBFieldAttribute;
    if (!attr.index && !attr.references) continue;
    if (attr.unique) continue; // already indexed by the unique constraint
    indexes.push(
      `    index(${quote(`${tableName}_${snake(name)}_idx`)}).on(t.${camel(name)}),`,
    );
  }

  const table_ = `sqliteTable(${quote(tableName)}, {\n${columns}\n}`;
  return indexes.length
    ? `export const ${camel(tableName)} = ${table_}, (t) => [\n${indexes.join("\n")}\n]);`
    : `export const ${camel(tableName)} = ${table_});`;
});

const source = `// GENERATED by \`bun run auth:generate\` (scripts/generate-auth-schema.ts).
// Do not edit; re-run after changing src/auth-options.ts.
import {
  sqliteTable,
  text,
  integer,
  index,
  uniqueIndex,
} from "drizzle-orm/sqlite-core";

${body.join("\n\n")}
`;

await Bun.write(OUT, source);
console.log(`wrote ${tables.length} tables to src/auth-schema.ts`);
